name: "CI"

on: [pull_request]

jobs:
  build:
    name: "Build, lint,"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Set up latest Node LTS"
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*"

      - name: "Install pnpm"
        run: npm install -g pnpm

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Check format"
        run: pnpm run format:check

      - name: "Build"
        run: pnpm run build

      - name: "Lint"
        run: pnpm run lint
